
# Jpa
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update

## H2 exemplo
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Define nível de log por pacote
logging.level.com.seuprojeto=DEBUG
logging.level.org.springframework=INFO

# Saída em arquivo
logging.file.name=logs/app.log


